<?php

namespace App\Repository;

/**
 * EffectueVacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EffectueVacationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findContactByEtablissementId($idEstablishment)
    {
        $sql = "SELECT eff_vaca
            FROM App\Entity\EffectueVacation eff_vaca JOIN eff_vaca.idEtablissement etab
            WHERE etab.id = ".$idEstablishment;

        $query =  $this->getEntityManager()
            ->createQuery(
                $sql
            );

        return $query->getResult();
    }
}
