<?php

namespace App\Repository;
use App\Entity\Etablissement;


/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEtablissementByEnterpriseName($enterprise_name){

        $sql = "SELECT etab FROM App\Entity\Etablissement etab JOIN etab.idEntreprise ent WHERE ent.nomEntreprise = '".$enterprise_name."'";
        //echo $sql;
        $query =  $this->getEntityManager()
            ->createQuery(
                $sql
            );

        return $query->getResult();
    }

    public function findEtablissementByEnterpriseNameAndCity($enterprise_name,$city_id){

        $sql = "SELECT etab FROM App\Entity\Etablissement etab JOIN etab.idEntreprise ent JOIN etab.idAdresse addr WHERE ent.nomEntreprise = '".$enterprise_name."' and addr.idVille = ".$city_id;
        //echo $sql;
        $query =  $this->getEntityManager()
            ->createQuery(
                $sql
            );

        return $query->getResult();
    }

    public function findEtablissementByCity($city_id){

        $sql = "SELECT addr FROM App\Entity\Adresse addr  WHERE addr.idVille = ".$city_id;
        //echo $sql;
        $query =  $this->getEntityManager()
            ->createQuery(
                $sql
            );
        //echo $query->getDQL();
        return $query->getResult();
    }
}
