<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipationForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationForumRepository extends \Doctrine\ORM\EntityRepository
{
}
