<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipationForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationForumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEtablissementByForum($forum)
    {
        $entityManager = $this->getEntityManager();
        $string = "Forum des entreprises Polytech Tours";

        $query = $entityManager->createQuery(
        'SELECT par_for
                FROM App\Entity\ParticipationForum par_for
                JOIN par_for.idForum forum
                JOIN forum.idTypeForum type_forum
                WHERE type_forum.libelleTypeForum = :nom_forum'
        )->setParameter('nom_forum', $forum);

        return $query->getResult();
    }
}
