index:
    path: /
    controller: App\Controller\MainPageController::index

connection:
    path: /connection
    controller: App\Controller\ConnectionController::index

import:
    path: /import
    controller: App\Controller\ImportController::index

pop_up:
    path: /pop_up
    controller: App\Controller\PopUpController::index

search:
    path: /search
    controller: App\Controller\SearchController::index

aproposentreprise:
    path: /aproposentreprise
    controller: App\Controller\AProposEntrepriseController::index

search_enterprise:
    path: /search_enterprise
    controller: App\Controller\SearchController::searchEnterprise