<?php declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180409143448 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE EstContactTechnique (id INT AUTO_INCREMENT NOT NULL, dateDebutContactTechnique DATE NOT NULL, dateFinContactTechnique DATE DEFAULT NULL, idContactEtablissement INT DEFAULT NULL, idPersonneContactEtablissement INT DEFAULT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_EstContactTechnique_ContactEtablissement1_idx (idContactEtablissement, idPersonneContactEtablissement), INDEX fk_EstContactTechnique_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Telephone (id INT AUTO_INCREMENT NOT NULL, numTelephone VARCHAR(45) NOT NULL, typeTelephone VARCHAR(45) NOT NULL, commentaireTelephone VARCHAR(100) DEFAULT NULL, UNIQUE INDEX numTelephone_UNIQUE (numTelephone), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Apprentissage (id INT AUTO_INCREMENT NOT NULL, dateDebutApprentissage DATE NOT NULL, dateFinApprentissage DATE DEFAULT NULL, dureeApprentissageAnnes INT NOT NULL COMMENT \'1 an, 3 ans, etc.\', etranger TINYINT(1) NOT NULL, detailsApprentissage TEXT DEFAULT NULL, idEtablissement INT DEFAULT NULL, idPersonneEtudiant INT DEFAULT NULL, idEtudiant INT DEFAULT NULL, idGratification INT DEFAULT NULL, idSpecialite INT DEFAULT NULL, INDEX fk_Apprentissage_Gratification1_idx (idGratification), INDEX fk_Apprentissage_Specialite1_idx (idSpecialite), INDEX fk_Apprentissage_Etudiant1_idx (idPersonneEtudiant, idEtudiant), INDEX fk_Apprentissage_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE EffectueVacation (id INT AUTO_INCREMENT NOT NULL, dateDebutVacation DATE NOT NULL, dateFinVacation DATE DEFAULT NULL, volumeHoraire INT NOT NULL, commentaireVacation VARCHAR(255) DEFAULT NULL, idContactEtablissement INT DEFAULT NULL, idPersonneContactEtablissement INT DEFAULT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_EffectueVacation_ContactEtablissement1_idx (idContactEtablissement, idPersonneContactEtablissement), INDEX fk_EffectueVacation_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Etudiant (id INT NOT NULL, numeroEtudiant INT NOT NULL, mailEtudiant VARCHAR(100) NOT NULL, anneeEtude INT NOT NULL, diplome TINYINT(1) NOT NULL COMMENT \'TRUE si diplomé, FAUX autrement\', dateDiplomation DATE DEFAULT NULL, idPersonne INT NOT NULL, idSpecialite INT DEFAULT NULL, idStartup INT DEFAULT NULL, INDEX fk_Etudiant_Startup1_idx (idStartup), INDEX fk_Etudiant_Personne1_idx (idPersonne), INDEX fk_Etudiant_Specialite1_idx (idSpecialite), UNIQUE INDEX numeroEtudiant_UNIQUE (numeroEtudiant), PRIMARY KEY(id, idPersonne)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE EstContactRH (id INT AUTO_INCREMENT NOT NULL, dateDebutContactRH DATE NOT NULL, dateFinContactRH DATE DEFAULT NULL, idContactEtablissement INT DEFAULT NULL, idPersonneContactEtablissement INT DEFAULT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_EstContactRH_ContactEtablissement1_idx (idContactEtablissement, idPersonneContactEtablissement), INDEX fk_EstContactRH_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Entreprise (id INT AUTO_INCREMENT NOT NULL, nomEntreprise VARCHAR(255) NOT NULL, numSIREN VARCHAR(9) NOT NULL, statutJuridique VARCHAR(45) NOT NULL, siteWebEntreprise VARCHAR(255) DEFAULT NULL, commentaireEntreprise TEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ProjetPedagogique (id INT AUTO_INCREMENT NOT NULL, dateDebutProjet DATE NOT NULL, intituleProjet VARCHAR(255) NOT NULL, detailsProjet TEXT DEFAULT NULL, montantAlloué DOUBLE PRECISION DEFAULT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_ProjetPedagogique_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Forum (id INT AUTO_INCREMENT NOT NULL, dateDebutForum DATETIME NOT NULL, dateFinForum DATETIME DEFAULT NULL, commentaireForum VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PersonnelPolytech (id INT NOT NULL, mailUniversitaire VARCHAR(100) NOT NULL, fonction VARCHAR(200) NOT NULL, idDepartement INT DEFAULT NULL, idPersonne INT NOT NULL, INDEX fk_PersonnelPolytech_Personne1_idx (idPersonne), INDEX fk_PersonnelPolytech_Departement1_idx (idDepartement), PRIMARY KEY(id, idPersonne)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Adresse (id INT AUTO_INCREMENT NOT NULL, adresse VARCHAR(200) NOT NULL, complementAdresse VARCHAR(200) DEFAULT NULL, codePostal VARCHAR(45) NOT NULL, Ville_idVille INT DEFAULT NULL, INDEX fk_Adresse_Ville1_idx (Ville_idVille), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Departement (id INT AUTO_INCREMENT NOT NULL, libelleDepartement VARCHAR(100) NOT NULL, UNIQUE INDEX libelleDepartement_UNIQUE (libelleDepartement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ConventionStage (id INT AUTO_INCREMENT NOT NULL, dateCreation DATE NOT NULL, dateDerniereModification DATE NOT NULL, typeConvention VARCHAR(45) DEFAULT NULL COMMENT \'Obligatoire, non obligatoire, ...\', validee TINYINT(1) NOT NULL, valideePedagogiquement TINYINT(1) NOT NULL, idContactEtablissementTuteur INT DEFAULT NULL, idPersonneContactEtablissementTuteur INT DEFAULT NULL, idContactEtablissementSignataire INT DEFAULT NULL, idPersonneContactEtablissementSignataire INT DEFAULT NULL, idEtablissement INT DEFAULT NULL, idEtudiant INT DEFAULT NULL, idPersonneEtudiant INT DEFAULT NULL, idGratification INT DEFAULT NULL, idPersonnelPolytechTuteur INT DEFAULT NULL, idPersonnePersonnelPolytechTuteur INT DEFAULT NULL, idPersonnelPolytechChargeSuivi INT DEFAULT NULL, idPersonnePersonnelPolytechChargeSuivi INT DEFAULT NULL, idServiceAccueil INT DEFAULT NULL, idSpecialite INT DEFAULT NULL, idStage INT DEFAULT NULL, INDEX fk_ConventionStage_Stage1_idx (idStage), INDEX fk_ConventionStage_Gratification1_idx (idGratification), INDEX fk_ConventionStage_Etudiant1_idx (idEtudiant, idPersonneEtudiant), INDEX fk_ConventionStage_Specialite1_idx (idSpecialite), INDEX fk_ConventionStage_PersonnelPolytech1_idx (idPersonnelPolytechTuteur, idPersonnePersonnelPolytechTuteur), INDEX fk_ConventionStage_PersonnelPolytech2_idx (idPersonnelPolytechChargeSuivi, idPersonnePersonnelPolytechChargeSuivi), INDEX fk_ConventionStage_ContactEtablissement1_idx (idContactEtablissementTuteur, idPersonneContactEtablissementTuteur), INDEX fk_ConventionStage_ContactEtablissement2_idx (idContactEtablissementSignataire, idPersonneContactEtablissementSignataire), INDEX fk_ConventionStage_Etablissement1_idx (idEtablissement), INDEX fk_ConventionStage_ServiceAccueil1_idx (idServiceAccueil), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Startup (id INT AUTO_INCREMENT NOT NULL, nomStartup VARCHAR(100) NOT NULL, dateCreationStartup DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE InterruptionStage (id INT AUTO_INCREMENT NOT NULL, dateDebutInterruption DATE NOT NULL, dateFinInterruption DATE NOT NULL, commentaireInterruption VARCHAR(255) DEFAULT NULL, idConventionStage INT DEFAULT NULL, INDEX fk_InterruptionStage_ConventionStage1_idx (idConventionStage), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Ville (id INT AUTO_INCREMENT NOT NULL, nomVille VARCHAR(200) NOT NULL, idPays INT DEFAULT NULL, INDEX fk_Ville_Pays1_idx (idPays), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Stage (id INT AUTO_INCREMENT NOT NULL, dateDebutStage DATE NOT NULL, dateFinStage DATE NOT NULL, anneeEtudeStage INT NOT NULL, thematiqueStage VARCHAR(255) NOT NULL, sujetStage VARCHAR(255) NOT NULL, fonctionsTachesStage TEXT NOT NULL, detailsProjetStage TEXT DEFAULT NULL, dureeStageSemaines INT NOT NULL, dureeStageHeures INT NOT NULL, nbJoursTravail INT NOT NULL, commentaireDureeStage VARCHAR(255) DEFAULT NULL, commentaireStage TEXT DEFAULT NULL, elementPedagogique VARCHAR(255) DEFAULT NULL, avantagesNature VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Etablissement (id INT AUTO_INCREMENT NOT NULL, nomEtablissement VARCHAR(200) NOT NULL, numSIRET VARCHAR(14) NOT NULL, typeStructure VARCHAR(45) DEFAULT NULL, effectifs VARCHAR(45) DEFAULT NULL, secteursActivites VARCHAR(200) DEFAULT NULL, codeNAF VARCHAR(45) DEFAULT NULL, siteWebEtablissement VARCHAR(255) DEFAULT NULL, commentaireEtablissement TEXT DEFAULT NULL, idAdresse INT DEFAULT NULL, idEntreprise INT DEFAULT NULL, INDEX fk_Etablissement_Adresse1_idx (idAdresse), INDEX fk_Etablissement_Entreprise1_idx (idEntreprise), UNIQUE INDEX siret_UNIQUE (numSIRET), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Personne (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(45) NOT NULL, prenom VARCHAR(45) NOT NULL, adresseMailPerso VARCHAR(100) DEFAULT NULL, codeSexe VARCHAR(1) DEFAULT NULL, nationalite VARCHAR(100) DEFAULT NULL, idAdresse INT DEFAULT NULL, INDEX fk_Personne_Adresse1_idx (idAdresse), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE possedetelephone (idPersonne INT NOT NULL, idTelephone INT NOT NULL, INDEX IDX_706F2DCE5C6DE3B4 (idPersonne), INDEX IDX_706F2DCEB9E5DB46 (idTelephone), PRIMARY KEY(idPersonne, idTelephone)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Conference (id INT AUTO_INCREMENT NOT NULL, dateConference DATE NOT NULL, heureDebutConference TIME DEFAULT NULL, heureFinConference TIME DEFAULT NULL, sujetConference VARCHAR(255) DEFAULT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_Conference_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE participeconference (idConference INT NOT NULL, idContactEtablissement INT NOT NULL, idPersonneContactEtablissement INT NOT NULL, INDEX IDX_2B407F3A13E12D22 (idConference), INDEX IDX_2B407F3AC505A774B91115B2 (idContactEtablissement, idPersonneContactEtablissement), PRIMARY KEY(idConference, idContactEtablissement, idPersonneContactEtablissement)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE VerseTaxeApprentissage (anneeVersement DATE NOT NULL, montantTaxe DOUBLE PRECISION NOT NULL, partieVersante VARCHAR(255) NOT NULL, idDepartement INT NOT NULL, idEtablissement INT NOT NULL, INDEX fk_VerseTaxeApprentissage_Etablissement1_idx (idEtablissement), INDEX IDX_D05CB0C0812BA41B (idDepartement), PRIMARY KEY(anneeVersement, idDepartement, idEtablissement)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ServiceAccueil (id INT AUTO_INCREMENT NOT NULL, nomService VARCHAR(100) NOT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_ServiceAccueil_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Gratification (id INT AUTO_INCREMENT NOT NULL, montantGratification DOUBLE PRECISION NOT NULL, uniteGratification VARCHAR(45) NOT NULL COMMENT \'BRUT / NET\', uniteDureeGratification VARCHAR(45) NOT NULL COMMENT \'HEURE, MOIS, etc.\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Pays (id INT AUTO_INCREMENT NOT NULL, nomPays VARCHAR(200) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Specialite (id INT AUTO_INCREMENT NOT NULL, libelleSpecialite VARCHAR(100) NOT NULL, idDepartement INT DEFAULT NULL, INDEX fk_Specialite_Departement1_idx (idDepartement), UNIQUE INDEX libelleSpecialite_UNIQUE (libelleSpecialite), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Avenant (id INT AUTO_INCREMENT NOT NULL, dateCreationAvenant DATE NOT NULL, objetAvenant VARCHAR(45) NOT NULL, detailsAvenant TEXT DEFAULT NULL, idConventionStage INT DEFAULT NULL, INDEX fk_Avenant_ConventionStage1_idx (idConventionStage), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ContactEtablissement (id INT NOT NULL, mailProfessionnel VARCHAR(100) DEFAULT NULL, fax VARCHAR(45) DEFAULT NULL, idPersonne INT NOT NULL, INDEX fk_ContactEtablissement_Personne1_idx (idPersonne), PRIMARY KEY(id, idPersonne)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE participeforum (idContactEtablissement INT NOT NULL, idPersonneContactEtablissement INT NOT NULL, idForum INT NOT NULL, INDEX IDX_1EDBD91AC505A774B91115B2 (idContactEtablissement, idPersonneContactEtablissement), INDEX IDX_1EDBD91A92EFFDD0 (idForum), PRIMARY KEY(idContactEtablissement, idPersonneContactEtablissement, idForum)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE EstEmploye (id INT AUTO_INCREMENT NOT NULL, dateDebutEmploi DATE NOT NULL, dateFinEmploi DATE DEFAULT NULL, fonction VARCHAR(255) NOT NULL, idContactEtablissement INT DEFAULT NULL, idPersonneContactEtablissement INT DEFAULT NULL, idEtablissement INT DEFAULT NULL, INDEX fk_Employe_ContactEtablissement1_idx (idContactEtablissement, idPersonneContactEtablissement), INDEX fk_Employe_Etablissement1_idx (idEtablissement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CIFRE (id INT AUTO_INCREMENT NOT NULL, intituleCIFRE VARCHAR(255) NOT NULL, dateDebutCIFRE DATE NOT NULL, soutenue TINYINT(1) NOT NULL, idEtablissement INT DEFAULT NULL, idPersonneEtudiant INT DEFAULT NULL, idEtudiant INT DEFAULT NULL, idPersonnePersonnelPolytech INT DEFAULT NULL, idPersonnelPolytech INT DEFAULT NULL, INDEX fk_CIFRE_Etudiant1_idx (idPersonneEtudiant, idEtudiant), INDEX fk_CIFRE_Etablissement1_idx (idEtablissement), INDEX fk_CIFRE_PersonnelPolytech1_idx (idPersonnePersonnelPolytech, idPersonnelPolytech), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ConseilPerfectionnement (id INT AUTO_INCREMENT NOT NULL, dateConseilPerfectionnement VARCHAR(45) NOT NULL, idDepartement INT DEFAULT NULL, INDEX fk_ConseilPerfectionnement_Departement1_idx (idDepartement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contactparticipeconseil (idConseilPerfectionnement INT NOT NULL, idPersonneContactEtablissement INT NOT NULL, idContactEtablissement INT NOT NULL, INDEX IDX_C45CE280BBE03F3F (idConseilPerfectionnement), INDEX IDX_C45CE280B91115B2C505A774 (idPersonneContactEtablissement, idContactEtablissement), PRIMARY KEY(idConseilPerfectionnement, idPersonneContactEtablissement, idContactEtablissement)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etudiantparticipeconseil (idConseilPerfectionnement INT NOT NULL, idPersonneEtudiant INT NOT NULL, idEtudiant INT NOT NULL, INDEX IDX_8312218BBE03F3F (idConseilPerfectionnement), INDEX IDX_8312218A1751A2C22DD08B8 (idPersonneEtudiant, idEtudiant), PRIMARY KEY(idConseilPerfectionnement, idPersonneEtudiant, idEtudiant)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE personnelparticipeconseil (idConseilPerfectionnement INT NOT NULL, idPersonnePersonnelPolytech INT NOT NULL, idPersonnelPolytech INT NOT NULL, INDEX IDX_7EB12243BBE03F3F (idConseilPerfectionnement), INDEX IDX_7EB1224394F783E4D1705DFF (idPersonnePersonnelPolytech, idPersonnelPolytech), PRIMARY KEY(idConseilPerfectionnement, idPersonnePersonnelPolytech, idPersonnelPolytech)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE EstContactTechnique ADD CONSTRAINT FK_8773FB56C505A774B91115B2 FOREIGN KEY (idContactEtablissement, idPersonneContactEtablissement) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE EstContactTechnique ADD CONSTRAINT FK_8773FB56EA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE Apprentissage ADD CONSTRAINT FK_3A7B080BEA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE Apprentissage ADD CONSTRAINT FK_3A7B080BA1751A2C22DD08B8 FOREIGN KEY (idPersonneEtudiant, idEtudiant) REFERENCES Etudiant (idPersonne, id)');
        $this->addSql('ALTER TABLE Apprentissage ADD CONSTRAINT FK_3A7B080B29F5FD74 FOREIGN KEY (idGratification) REFERENCES Gratification (id)');
        $this->addSql('ALTER TABLE Apprentissage ADD CONSTRAINT FK_3A7B080B6522E22B FOREIGN KEY (idSpecialite) REFERENCES Specialite (id)');
        $this->addSql('ALTER TABLE EffectueVacation ADD CONSTRAINT FK_D7B62B8EC505A774B91115B2 FOREIGN KEY (idContactEtablissement, idPersonneContactEtablissement) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE EffectueVacation ADD CONSTRAINT FK_D7B62B8EEA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE Etudiant ADD CONSTRAINT FK_880840B55C6DE3B4 FOREIGN KEY (idPersonne) REFERENCES Personne (id)');
        $this->addSql('ALTER TABLE Etudiant ADD CONSTRAINT FK_880840B56522E22B FOREIGN KEY (idSpecialite) REFERENCES Specialite (id)');
        $this->addSql('ALTER TABLE Etudiant ADD CONSTRAINT FK_880840B5F4373B04 FOREIGN KEY (idStartup) REFERENCES Startup (id)');
        $this->addSql('ALTER TABLE EstContactRH ADD CONSTRAINT FK_C02AD2CDC505A774B91115B2 FOREIGN KEY (idContactEtablissement, idPersonneContactEtablissement) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE EstContactRH ADD CONSTRAINT FK_C02AD2CDEA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE ProjetPedagogique ADD CONSTRAINT FK_15603FEAEA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE PersonnelPolytech ADD CONSTRAINT FK_9B3B7D9A812BA41B FOREIGN KEY (idDepartement) REFERENCES Departement (id)');
        $this->addSql('ALTER TABLE PersonnelPolytech ADD CONSTRAINT FK_9B3B7D9A5C6DE3B4 FOREIGN KEY (idPersonne) REFERENCES Personne (id)');
        $this->addSql('ALTER TABLE Adresse ADD CONSTRAINT FK_CE2318AD16C7897 FOREIGN KEY (Ville_idVille) REFERENCES Ville (id)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E560A3E38F968CC578B7 FOREIGN KEY (idContactEtablissementTuteur, idPersonneContactEtablissementTuteur) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E560C2DBFCCD2D1EFBE FOREIGN KEY (idContactEtablissementSignataire, idPersonneContactEtablissementSignataire) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E560EA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E56022DD08B8A1751A2C FOREIGN KEY (idEtudiant, idPersonneEtudiant) REFERENCES Etudiant (id, idPersonne)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E56029F5FD74 FOREIGN KEY (idGratification) REFERENCES Gratification (id)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E56092DE7873CBD58ABA FOREIGN KEY (idPersonnelPolytechTuteur, idPersonnePersonnelPolytechTuteur) REFERENCES PersonnelPolytech (id, idPersonne)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E56010C25C9DBF8401E7 FOREIGN KEY (idPersonnelPolytechChargeSuivi, idPersonnePersonnelPolytechChargeSuivi) REFERENCES PersonnelPolytech (id, idPersonne)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E560D6CC7E04 FOREIGN KEY (idServiceAccueil) REFERENCES ServiceAccueil (id)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E5606522E22B FOREIGN KEY (idSpecialite) REFERENCES Specialite (id)');
        $this->addSql('ALTER TABLE ConventionStage ADD CONSTRAINT FK_EFA7E560D5B8D074 FOREIGN KEY (idStage) REFERENCES Stage (id)');
        $this->addSql('ALTER TABLE InterruptionStage ADD CONSTRAINT FK_EB13A8A1EB805E9 FOREIGN KEY (idConventionStage) REFERENCES ConventionStage (id)');
        $this->addSql('ALTER TABLE Ville ADD CONSTRAINT FK_8202F6C747626230 FOREIGN KEY (idPays) REFERENCES Pays (id)');
        $this->addSql('ALTER TABLE Etablissement ADD CONSTRAINT FK_938312D9D3E663E4 FOREIGN KEY (idAdresse) REFERENCES Adresse (id)');
        $this->addSql('ALTER TABLE Etablissement ADD CONSTRAINT FK_938312D98FEDE48A FOREIGN KEY (idEntreprise) REFERENCES Entreprise (id)');
        $this->addSql('ALTER TABLE Personne ADD CONSTRAINT FK_F6B8ABB9D3E663E4 FOREIGN KEY (idAdresse) REFERENCES Adresse (id)');
        $this->addSql('ALTER TABLE possedetelephone ADD CONSTRAINT FK_706F2DCE5C6DE3B4 FOREIGN KEY (idPersonne) REFERENCES Personne (id)');
        $this->addSql('ALTER TABLE possedetelephone ADD CONSTRAINT FK_706F2DCEB9E5DB46 FOREIGN KEY (idTelephone) REFERENCES Telephone (id)');
        $this->addSql('ALTER TABLE Conference ADD CONSTRAINT FK_DE483018EA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE participeconference ADD CONSTRAINT FK_2B407F3A13E12D22 FOREIGN KEY (idConference) REFERENCES Conference (id)');
        $this->addSql('ALTER TABLE participeconference ADD CONSTRAINT FK_2B407F3AC505A774B91115B2 FOREIGN KEY (idContactEtablissement, idPersonneContactEtablissement) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE VerseTaxeApprentissage ADD CONSTRAINT FK_D05CB0C0812BA41B FOREIGN KEY (idDepartement) REFERENCES Departement (id)');
        $this->addSql('ALTER TABLE VerseTaxeApprentissage ADD CONSTRAINT FK_D05CB0C0EA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE ServiceAccueil ADD CONSTRAINT FK_C7B4EF4FEA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE Specialite ADD CONSTRAINT FK_A88BFF11812BA41B FOREIGN KEY (idDepartement) REFERENCES Departement (id)');
        $this->addSql('ALTER TABLE Avenant ADD CONSTRAINT FK_CD436579EB805E9 FOREIGN KEY (idConventionStage) REFERENCES ConventionStage (id)');
        $this->addSql('ALTER TABLE ContactEtablissement ADD CONSTRAINT FK_FF93124F5C6DE3B4 FOREIGN KEY (idPersonne) REFERENCES Personne (id)');
        $this->addSql('ALTER TABLE participeforum ADD CONSTRAINT FK_1EDBD91AC505A774B91115B2 FOREIGN KEY (idContactEtablissement, idPersonneContactEtablissement) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE participeforum ADD CONSTRAINT FK_1EDBD91A92EFFDD0 FOREIGN KEY (idForum) REFERENCES Forum (id)');
        $this->addSql('ALTER TABLE EstEmploye ADD CONSTRAINT FK_D0F8F1B3C505A774B91115B2 FOREIGN KEY (idContactEtablissement, idPersonneContactEtablissement) REFERENCES ContactEtablissement (id, idPersonne)');
        $this->addSql('ALTER TABLE EstEmploye ADD CONSTRAINT FK_D0F8F1B3EA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE CIFRE ADD CONSTRAINT FK_C541B988EA190502 FOREIGN KEY (idEtablissement) REFERENCES Etablissement (id)');
        $this->addSql('ALTER TABLE CIFRE ADD CONSTRAINT FK_C541B988A1751A2C22DD08B8 FOREIGN KEY (idPersonneEtudiant, idEtudiant) REFERENCES Etudiant (idPersonne, id)');
        $this->addSql('ALTER TABLE CIFRE ADD CONSTRAINT FK_C541B98894F783E4D1705DFF FOREIGN KEY (idPersonnePersonnelPolytech, idPersonnelPolytech) REFERENCES PersonnelPolytech (idPersonne, id)');
        $this->addSql('ALTER TABLE ConseilPerfectionnement ADD CONSTRAINT FK_130059F8812BA41B FOREIGN KEY (idDepartement) REFERENCES Departement (id)');
        $this->addSql('ALTER TABLE contactparticipeconseil ADD CONSTRAINT FK_C45CE280BBE03F3F FOREIGN KEY (idConseilPerfectionnement) REFERENCES ConseilPerfectionnement (id)');
        $this->addSql('ALTER TABLE contactparticipeconseil ADD CONSTRAINT FK_C45CE280B91115B2C505A774 FOREIGN KEY (idPersonneContactEtablissement, idContactEtablissement) REFERENCES ContactEtablissement (idPersonne, id)');
        $this->addSql('ALTER TABLE etudiantparticipeconseil ADD CONSTRAINT FK_8312218BBE03F3F FOREIGN KEY (idConseilPerfectionnement) REFERENCES ConseilPerfectionnement (id)');
        $this->addSql('ALTER TABLE etudiantparticipeconseil ADD CONSTRAINT FK_8312218A1751A2C22DD08B8 FOREIGN KEY (idPersonneEtudiant, idEtudiant) REFERENCES Etudiant (idPersonne, id)');
        $this->addSql('ALTER TABLE personnelparticipeconseil ADD CONSTRAINT FK_7EB12243BBE03F3F FOREIGN KEY (idConseilPerfectionnement) REFERENCES ConseilPerfectionnement (id)');
        $this->addSql('ALTER TABLE personnelparticipeconseil ADD CONSTRAINT FK_7EB1224394F783E4D1705DFF FOREIGN KEY (idPersonnePersonnelPolytech, idPersonnelPolytech) REFERENCES PersonnelPolytech (idPersonne, id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE possedetelephone DROP FOREIGN KEY FK_706F2DCEB9E5DB46');
        $this->addSql('ALTER TABLE Apprentissage DROP FOREIGN KEY FK_3A7B080BA1751A2C22DD08B8');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E56022DD08B8A1751A2C');
        $this->addSql('ALTER TABLE CIFRE DROP FOREIGN KEY FK_C541B988A1751A2C22DD08B8');
        $this->addSql('ALTER TABLE etudiantparticipeconseil DROP FOREIGN KEY FK_8312218A1751A2C22DD08B8');
        $this->addSql('ALTER TABLE Etablissement DROP FOREIGN KEY FK_938312D98FEDE48A');
        $this->addSql('ALTER TABLE participeforum DROP FOREIGN KEY FK_1EDBD91A92EFFDD0');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E56092DE7873CBD58ABA');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E56010C25C9DBF8401E7');
        $this->addSql('ALTER TABLE CIFRE DROP FOREIGN KEY FK_C541B98894F783E4D1705DFF');
        $this->addSql('ALTER TABLE personnelparticipeconseil DROP FOREIGN KEY FK_7EB1224394F783E4D1705DFF');
        $this->addSql('ALTER TABLE Etablissement DROP FOREIGN KEY FK_938312D9D3E663E4');
        $this->addSql('ALTER TABLE Personne DROP FOREIGN KEY FK_F6B8ABB9D3E663E4');
        $this->addSql('ALTER TABLE PersonnelPolytech DROP FOREIGN KEY FK_9B3B7D9A812BA41B');
        $this->addSql('ALTER TABLE VerseTaxeApprentissage DROP FOREIGN KEY FK_D05CB0C0812BA41B');
        $this->addSql('ALTER TABLE Specialite DROP FOREIGN KEY FK_A88BFF11812BA41B');
        $this->addSql('ALTER TABLE ConseilPerfectionnement DROP FOREIGN KEY FK_130059F8812BA41B');
        $this->addSql('ALTER TABLE InterruptionStage DROP FOREIGN KEY FK_EB13A8A1EB805E9');
        $this->addSql('ALTER TABLE Avenant DROP FOREIGN KEY FK_CD436579EB805E9');
        $this->addSql('ALTER TABLE Etudiant DROP FOREIGN KEY FK_880840B5F4373B04');
        $this->addSql('ALTER TABLE Adresse DROP FOREIGN KEY FK_CE2318AD16C7897');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E560D5B8D074');
        $this->addSql('ALTER TABLE EstContactTechnique DROP FOREIGN KEY FK_8773FB56EA190502');
        $this->addSql('ALTER TABLE Apprentissage DROP FOREIGN KEY FK_3A7B080BEA190502');
        $this->addSql('ALTER TABLE EffectueVacation DROP FOREIGN KEY FK_D7B62B8EEA190502');
        $this->addSql('ALTER TABLE EstContactRH DROP FOREIGN KEY FK_C02AD2CDEA190502');
        $this->addSql('ALTER TABLE ProjetPedagogique DROP FOREIGN KEY FK_15603FEAEA190502');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E560EA190502');
        $this->addSql('ALTER TABLE Conference DROP FOREIGN KEY FK_DE483018EA190502');
        $this->addSql('ALTER TABLE VerseTaxeApprentissage DROP FOREIGN KEY FK_D05CB0C0EA190502');
        $this->addSql('ALTER TABLE ServiceAccueil DROP FOREIGN KEY FK_C7B4EF4FEA190502');
        $this->addSql('ALTER TABLE EstEmploye DROP FOREIGN KEY FK_D0F8F1B3EA190502');
        $this->addSql('ALTER TABLE CIFRE DROP FOREIGN KEY FK_C541B988EA190502');
        $this->addSql('ALTER TABLE Etudiant DROP FOREIGN KEY FK_880840B55C6DE3B4');
        $this->addSql('ALTER TABLE PersonnelPolytech DROP FOREIGN KEY FK_9B3B7D9A5C6DE3B4');
        $this->addSql('ALTER TABLE possedetelephone DROP FOREIGN KEY FK_706F2DCE5C6DE3B4');
        $this->addSql('ALTER TABLE ContactEtablissement DROP FOREIGN KEY FK_FF93124F5C6DE3B4');
        $this->addSql('ALTER TABLE participeconference DROP FOREIGN KEY FK_2B407F3A13E12D22');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E560D6CC7E04');
        $this->addSql('ALTER TABLE Apprentissage DROP FOREIGN KEY FK_3A7B080B29F5FD74');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E56029F5FD74');
        $this->addSql('ALTER TABLE Ville DROP FOREIGN KEY FK_8202F6C747626230');
        $this->addSql('ALTER TABLE Apprentissage DROP FOREIGN KEY FK_3A7B080B6522E22B');
        $this->addSql('ALTER TABLE Etudiant DROP FOREIGN KEY FK_880840B56522E22B');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E5606522E22B');
        $this->addSql('ALTER TABLE EstContactTechnique DROP FOREIGN KEY FK_8773FB56C505A774B91115B2');
        $this->addSql('ALTER TABLE EffectueVacation DROP FOREIGN KEY FK_D7B62B8EC505A774B91115B2');
        $this->addSql('ALTER TABLE EstContactRH DROP FOREIGN KEY FK_C02AD2CDC505A774B91115B2');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E560A3E38F968CC578B7');
        $this->addSql('ALTER TABLE ConventionStage DROP FOREIGN KEY FK_EFA7E560C2DBFCCD2D1EFBE');
        $this->addSql('ALTER TABLE participeconference DROP FOREIGN KEY FK_2B407F3AC505A774B91115B2');
        $this->addSql('ALTER TABLE participeforum DROP FOREIGN KEY FK_1EDBD91AC505A774B91115B2');
        $this->addSql('ALTER TABLE EstEmploye DROP FOREIGN KEY FK_D0F8F1B3C505A774B91115B2');
        $this->addSql('ALTER TABLE contactparticipeconseil DROP FOREIGN KEY FK_C45CE280B91115B2C505A774');
        $this->addSql('ALTER TABLE contactparticipeconseil DROP FOREIGN KEY FK_C45CE280BBE03F3F');
        $this->addSql('ALTER TABLE etudiantparticipeconseil DROP FOREIGN KEY FK_8312218BBE03F3F');
        $this->addSql('ALTER TABLE personnelparticipeconseil DROP FOREIGN KEY FK_7EB12243BBE03F3F');
        $this->addSql('DROP TABLE EstContactTechnique');
        $this->addSql('DROP TABLE Telephone');
        $this->addSql('DROP TABLE Apprentissage');
        $this->addSql('DROP TABLE EffectueVacation');
        $this->addSql('DROP TABLE Etudiant');
        $this->addSql('DROP TABLE EstContactRH');
        $this->addSql('DROP TABLE Entreprise');
        $this->addSql('DROP TABLE ProjetPedagogique');
        $this->addSql('DROP TABLE Forum');
        $this->addSql('DROP TABLE PersonnelPolytech');
        $this->addSql('DROP TABLE Adresse');
        $this->addSql('DROP TABLE Departement');
        $this->addSql('DROP TABLE ConventionStage');
        $this->addSql('DROP TABLE Startup');
        $this->addSql('DROP TABLE InterruptionStage');
        $this->addSql('DROP TABLE Ville');
        $this->addSql('DROP TABLE Stage');
        $this->addSql('DROP TABLE Etablissement');
        $this->addSql('DROP TABLE Personne');
        $this->addSql('DROP TABLE possedetelephone');
        $this->addSql('DROP TABLE Conference');
        $this->addSql('DROP TABLE participeconference');
        $this->addSql('DROP TABLE VerseTaxeApprentissage');
        $this->addSql('DROP TABLE ServiceAccueil');
        $this->addSql('DROP TABLE Gratification');
        $this->addSql('DROP TABLE Pays');
        $this->addSql('DROP TABLE Specialite');
        $this->addSql('DROP TABLE Avenant');
        $this->addSql('DROP TABLE ContactEtablissement');
        $this->addSql('DROP TABLE participeforum');
        $this->addSql('DROP TABLE EstEmploye');
        $this->addSql('DROP TABLE CIFRE');
        $this->addSql('DROP TABLE ConseilPerfectionnement');
        $this->addSql('DROP TABLE contactparticipeconseil');
        $this->addSql('DROP TABLE etudiantparticipeconseil');
        $this->addSql('DROP TABLE personnelparticipeconseil');
    }
}
